# Generated by Django 6.0.4 on 2026-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_arrival_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arrivalitem",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество"),
        ),
    ]
