import re

SPECIAL_CHARS = r"!@#$%^&*()_+\-=\[\]{};':\"\\|,.<>\/?`~\s"

ONLY_CYRILLIC_LATIN_SPECIAL_SYMBOLS_AND_NUMBERS_STRING_REGEX = rf'^[а-яА-ЯёЁa-zA-Z\d{SPECIAL_CHARS}]+$'

ONLY_SYMBOLS_AND_SPECIAL_SYMBOLS_STRING_REGEX =rf'^[а-яА-ЯёЁa-zA-Z{SPECIAL_CHARS}]+$'

ONLY_SYMBOLS_STRING_REGEX = r'^[а-яА-ЯёЁa-zA-Z\s]+$'

ONLY_CYRILLIC_STRING_REGEX = r'^[а-яА-ЯёЁ\s]+$'

ONLY_LATIN_STRING_REGEX = r'^[a-zA-Z\s]+$'

ONLY_NUMBERS_REGEX = r'^\d+$'

PHONE_NUMBER_REGEX = r'^(\+7|8)[\s\-]?\(?\d{3}\)?[\s\-]?\d{3}[\s\-]?\d{2}[\s\-]?\d{2}$'

__all__ = [
    "ONLY_CYRILLIC_LATIN_SPECIAL_SYMBOLS_AND_NUMBERS_STRING_REGEX",
    "ONLY_SYMBOLS_AND_SPECIAL_SYMBOLS_STRING_REGEX",
    "ONLY_SYMBOLS_STRING_REGEX",
    "ONLY_CYRILLIC_STRING_REGEX",
    "ONLY_LATIN_STRING_REGEX",
    "PHONE_NUMBER_REGEX",
    "ONLY_NUMBERS_REGEX",
]