# Generated by Django 6.0.4 on 2026-04-29 00:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название типа препарата (лекарства) уже существует в системе",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название типа препарата (лекарства) должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Название типа препарата (лекарства) должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=200,
                                message="Название типа препарата (лекарства) должен иметь максимальную длину 200 симв.",
                            ),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название произодителя уже существует в системе.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название произодителя должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=200,
                                message="Название произодителя должен иметь минимальную длину 200 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Название произодителя должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такая страна уже связана с другим производителем.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Страна должен состоять только из букв и пробелов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=57,
                                message="Страна должен иметь минимальную длину 57 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Страна должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        error_messages={
                            "required": "Эта контактная информация обязательна.",
                            "unique": "Такой номер телефона уже связан с другим производителем.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона может состоять из цифр, скобок и пробелов",
                                regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "required": "Эта контактная информация обязательна.",
                            "unique": "Такой адрес электронной почты уже связан с другим производителем.",
                        },
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("other_info", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
