# Generated by Django 6.0.4 on 2026-05-07 22:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название типа препарата (лекарства) уже существует в системе",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название типа препарата (лекарства) должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Название типа препарата (лекарства) должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=200,
                                message="Название типа препарата (лекарства) должен иметь максимальную длину 200 симв.",
                            ),
                        ],
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название произодителя уже существует в системе.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название произодителя должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=200,
                                message="Название произодителя должен иметь минимальную длину 200 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Название произодителя должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такая страна уже связана с другим производителем.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Страна должен состоять только из букв и пробелов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=57,
                                message="Страна должен иметь минимальную длину 57 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Страна должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                        verbose_name="Страна",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        error_messages={
                            "required": "Эта контактная информация обязательна.",
                            "unique": "Такой номер телефона уже связан с другим производителем.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона может состоять из цифр, скобок и пробелов.",
                                regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "required": "Эта контактная информация обязательна.",
                            "unique": "Такой адрес электронной почты уже связан с другим производителем.",
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "other_info",
                    models.TextField(
                        blank=True, default="", verbose_name="Дополнительная информация"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        default="...",
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название поставщика уже существует в системе.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название поставщика должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=255,
                                message="Название поставщика должен иметь минимальную длину 255 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Название поставщика должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                        verbose_name="Название поставщика",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        default="",
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название поставщика уже существует в системе.",
                        },
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название поставщика должен состоять только из латиницы и пробелов.",
                                regex="^[a-zA-Z\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=255,
                                message="Название поставщика должен иметь минимальную длину 255 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Название поставщика должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                        verbose_name="Название поставщика на английском языке (для заграничных поставщиков)",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "inn",
                    models.CharField(
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ИНН должен содержать 10 или 12 цифр.",
                                regex="^\\d{10}(\\d{2})?$",
                            )
                        ],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="КПП должен содержать 9 цифр.", regex="^\\d{9}$"
                            )
                        ],
                        verbose_name="КПП",
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ОГРН должен содержать 13 или 15 цифр.",
                                regex="^\\d{13}(\\d{2})?$",
                            )
                        ],
                        verbose_name="ОГРН",
                    ),
                ),
                (
                    "oktmo",
                    models.CharField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ОКТМО должен содержать 8 или 11 цифр.",
                                regex="^\\d{8}(\\d{3})?$",
                            )
                        ],
                        verbose_name="ОКТМО",
                    ),
                ),
                (
                    "pharma_license_number",
                    models.CharField(
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер лицензии (согласно РосЗдравНадзор) должен иметь формат 'ЛО-77-02-123456'",
                                regex="^ЛО-\\d{2}-\\d{2}-\\d+$",
                            )
                        ],
                        verbose_name="Номер лицензии (согласно РосЗдравНадзор)",
                    ),
                ),
                (
                    "pharma_license_date",
                    models.DateField(null=True, verbose_name="Дата выдачи лицензии"),
                ),
                (
                    "pharma_license_expiry",
                    models.DateField(null=True, verbose_name="Дата окончания лицензии"),
                ),
                (
                    "legal_address",
                    models.TextField(blank=True, verbose_name="Юридический адрес"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        error_messages={
                            "required": "Данная контактная информация обязательна.",
                            "unique": "Такой номер телефона уже связан с другим поставщиком.",
                        },
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона может состоять из цифр, скобок и пробелов.",
                                regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "required": "Данная контактная информация обязательна.",
                            "unique": "Такой адрес электронной почты уже связан с другим поставщиком.",
                        },
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        default="...",
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такой препарат уже существует в системе.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Препарат должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=255,
                                message="Препарат должен иметь минимальную длину 255 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Препарат должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                        verbose_name="Препарат",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.druggroup",
                        verbose_name="Группа препаратов",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.manufacturer",
                        verbose_name="Произодитель",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
