# Generated by Django 6.0.4 on 2026-04-29 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={
                    "required": "Данная контактная информация обязательна.",
                    "unique": "Такой адрес электронной почты уже связан с другим поставщиком.",
                },
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Адрес электронной почты",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="inn",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ИНН должен содержать 10 или 12 цифр.",
                        regex="^\\d{10}(\\d{2})?$",
                    )
                ],
                verbose_name="ИНН",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="kpp",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="КПП должен содержать 9 цифр.", regex="^\\d{9}$"
                    )
                ],
                verbose_name="КПП",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="legal_address",
            field=models.TextField(blank=True, verbose_name="Юридический адрес"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                default="...",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название поставщика уже существует в системе.",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название поставщика должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=255,
                        message="Название поставщика должен иметь минимальную длину 255 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=3,
                        message="Название поставщика должен иметь максимальную длину 3 симв.",
                    ),
                ],
                verbose_name="Название поставщика",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="name_en",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название поставщика уже существует в системе.",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название поставщика должен состоять только из латиницы и пробелов.",
                        regex="^[a-zA-Z\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=255,
                        message="Название поставщика должен иметь минимальную длину 255 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=3,
                        message="Название поставщика должен иметь максимальную длину 3 симв.",
                    ),
                ],
                verbose_name="Название поставщика на английском языке (для заграничных поставщиков)",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="ogrn",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ОГРН должен содержать 13 или 15 цифр.",
                        regex="^\\d{13}(\\d{2})?$",
                    )
                ],
                verbose_name="ОГРН",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="oktmo",
            field=models.CharField(
                blank=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ОКТМО должен содержать 8 или 11 цифр.",
                        regex="^\\d{8}(\\d{3})?$",
                    )
                ],
                verbose_name="ОКТМО",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="pharma_license_date",
            field=models.DateField(null=True, verbose_name="Дата выдачи лицензии"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="pharma_license_expiry",
            field=models.DateField(null=True, verbose_name="Дата окончания лицензии"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="pharma_license_number",
            field=models.CharField(
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер лицензии (согласно РосЗдравНадзор) должен иметь формат 'ЛО-77-02-123456'",
                        regex="^ЛО-\\d{2}-\\d{2}-\\d+$",
                    )
                ],
                verbose_name="Номер лицензии (согласно РосЗдравНадзор)",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={
                    "required": "Данная контактная информация обязательна.",
                    "unique": "Такой номер телефона уже связан с другим поставщиком.",
                },
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона может состоять из цифр, скобок и пробелов.",
                        regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="druggroup",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="druggroup",
            name="name",
            field=models.CharField(
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название типа препарата (лекарства) уже существует в системе",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название типа препарата (лекарства) должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Название типа препарата (лекарства) должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=200,
                        message="Название типа препарата (лекарства) должен иметь максимальную длину 200 симв.",
                    ),
                ],
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такая страна уже связана с другим производителем.",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Страна должен состоять только из букв и пробелов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=57,
                        message="Страна должен иметь минимальную длину 57 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=3,
                        message="Страна должен иметь максимальную длину 3 симв.",
                    ),
                ],
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="email",
            field=models.EmailField(
                error_messages={
                    "required": "Эта контактная информация обязательна.",
                    "unique": "Такой адрес электронной почты уже связан с другим производителем.",
                },
                max_length=254,
                unique=True,
                verbose_name="Адрес электронной почты",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название произодителя уже существует в системе.",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название произодителя должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=200,
                        message="Название произодителя должен иметь минимальную длину 200 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=3,
                        message="Название произодителя должен иметь максимальную длину 3 симв.",
                    ),
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="other_info",
            field=models.TextField(
                blank=True, default="", verbose_name="Дополнительная информация"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="phone_number",
            field=models.CharField(
                error_messages={
                    "required": "Эта контактная информация обязательна.",
                    "unique": "Такой номер телефона уже связан с другим производителем.",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона может состоять из цифр, скобок и пробелов.",
                        regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
