# Generated by Django 6.0.4 on 2026-05-09 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="name",
            field=models.CharField(
                default="...",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такой препарат уже существует в системе.",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Препарат должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Препарат должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=255,
                        message="Препарат должен иметь максимальную длину 255 симв.",
                    ),
                ],
                verbose_name="Препарат",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такая страна уже связана с другим производителем.",
                },
                validators=[
                    django.core.validators.RegexValidator(
                        message="Страна должен состоять только из букв и пробелов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Страна должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=57,
                        message="Страна должен иметь максимальную длину 57 симв.",
                    ),
                ],
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название произодителя уже существует в системе.",
                },
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название произодителя должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Название произодителя должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=200,
                        message="Название произодителя должен иметь максимальную длину 200 симв.",
                    ),
                ],
                verbose_name="Название",
            ),
        ),
    ]
