# Generated by Django 6.0.4 on 2026-04-29 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_supplier_description_supplier_email_supplier_inn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                error_messages={
                    "required": "Данная контактная информация обязательна.",
                    "unique": "Такой адрес электронной почты уже связан с другим поставщиком.",
                },
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Адрес электронной почты",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="inn",
            field=models.CharField(
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ИНН должен содержать 10 или 12 цифр.",
                        regex="^\\d{10}(\\d{2})?$",
                    )
                ],
                verbose_name="ИНН",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name_en",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название поставщика уже существует в системе.",
                },
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название поставщика должен состоять только из латиницы и пробелов.",
                        regex="^[a-zA-Z\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=255,
                        message="Название поставщика должен иметь минимальную длину 255 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=3,
                        message="Название поставщика должен иметь максимальную длину 3 симв.",
                    ),
                ],
                verbose_name="Название поставщика на английском языке (для заграничных поставщиков)",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="ogrn",
            field=models.CharField(
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ОГРН должен содержать 13 или 15 цифр.",
                        regex="^\\d{13}(\\d{2})?$",
                    )
                ],
                verbose_name="ОГРН",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="oktmo",
            field=models.CharField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ОКТМО должен содержать 8 или 11 цифр.",
                        regex="^\\d{8}(\\d{3})?$",
                    )
                ],
                verbose_name="ОКТМО",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(
                error_messages={
                    "required": "Данная контактная информация обязательна.",
                    "unique": "Такой номер телефона уже связан с другим поставщиком.",
                },
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона может состоять из цифр, скобок и пробелов.",
                        regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
