# Generated by Django 6.0.4 on 2026-05-09 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_drug_name_alter_manufacturer_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="name",
            field=models.CharField(
                default="...",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такой препарат уже существует в системе.",
                },
                validators=[
                    django.core.validators.RegexValidator(
                        message="Препарат должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Препарат должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=255,
                        message="Препарат должен иметь максимальную длину 255 симв.",
                    ),
                ],
                verbose_name="Препарат",
            ),
        ),
    ]
