# Generated by Django 6.0.4 on 2026-05-09 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_drug_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="druggroup",
            name="name",
            field=models.CharField(
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название типа препарата (лекарства) уже существует в системе",
                },
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название типа препарата (лекарства) должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Название типа препарата (лекарства) должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=200,
                        message="Название типа препарата (лекарства) должен иметь максимальную длину 200 симв.",
                    ),
                ],
                verbose_name="Наименование",
            ),
        ),
    ]
