# Generated by Django 6.0.4 on 2026-04-29 13:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_supplier_email_alter_supplier_inn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        default="...",
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такой препарат уже существует в системе.",
                        },
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Препарат должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=255,
                                message="Препарат должен иметь минимальную длину 255 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=3,
                                message="Препарат должен иметь максимальную длину 3 симв.",
                            ),
                        ],
                        verbose_name="Препарат",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.manufacturer",
                        verbose_name="Произодитель",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
