# Generated by Django 6.0.4 on 2026-05-09 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_druggroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название произодителя уже существует в системе.",
                },
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название произодителя должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Название произодителя должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=200,
                        message="Название произодителя должен иметь максимальную длину 200 симв.",
                    ),
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name_en",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название поставщика уже существует в системе.",
                },
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название поставщика должен состоять только из латиницы и пробелов.",
                        regex="^[a-zA-Z\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=255,
                        message="Название поставщика должен иметь минимальную длину 255 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=3,
                        message="Название поставщика должен иметь максимальную длину 3 симв.",
                    ),
                ],
                verbose_name="Название поставщика на английском языке (для заграничных поставщиков)",
            ),
        ),
    ]
