# Generated by Django 6.0.4 on 2026-05-09 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_manufacturer_name_alter_supplier_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                default="...",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название поставщика уже существует в системе.",
                },
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название поставщика должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=255,
                        message="Название поставщика должен иметь минимальную длину 255 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=3,
                        message="Название поставщика должен иметь максимальную длину 3 симв.",
                    ),
                ],
                verbose_name="Название поставщика",
            ),
        ),
    ]
