# Generated by Django 6.0.4 on 2026-05-09 15:20

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_supplier_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                default="...",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название поставщика уже существует в системе.",
                },
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название поставщика должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Название поставщика должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=255,
                        message="Название поставщика должен иметь максимальную длину 255 симв.",
                    ),
                ],
                verbose_name="Название поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name_en",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={
                    "required": "Это поле обязательно",
                    "unique": "Такое название поставщика уже существует в системе.",
                },
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название поставщика должен состоять только из букв, цифр, пробелов и спецсимволов.",
                        regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3,
                        message="Название поставщика должен иметь минимальную длину 3 симв.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=255,
                        message="Название поставщика должен иметь максимальную длину 255 симв.",
                    ),
                ],
                verbose_name="Название поставщика на английском языке (для заграничных поставщиков)",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="pharma_license_number",
            field=models.CharField(
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер лицензии (согласно РосЗдравНадзор) должен иметь формат 'ЛО-77-02-123456'",
                        regex="^ЛО-\\d{2}-\\d{2}-\\d{10}$",
                    )
                ],
                verbose_name="Номер лицензии (согласно РосЗдравНадзор)",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalDrug",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        default="...",
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такой препарат уже существует в системе.",
                        },
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Препарат должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Препарат должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=255,
                                message="Препарат должен иметь максимальную длину 255 симв.",
                            ),
                        ],
                        verbose_name="Препарат",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.druggroup",
                        verbose_name="Группа препаратов",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.manufacturer",
                        verbose_name="Произодитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical drug",
                "verbose_name_plural": "historical drugs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDrugGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название типа препарата (лекарства) уже существует в системе",
                        },
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название типа препарата (лекарства) должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Название типа препарата (лекарства) должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=200,
                                message="Название типа препарата (лекарства) должен иметь максимальную длину 200 симв.",
                            ),
                        ],
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical drug group",
                "verbose_name_plural": "historical drug groups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalManufacturer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название произодителя уже существует в системе.",
                        },
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название произодителя должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Название произодителя должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=200,
                                message="Название произодителя должен иметь максимальную длину 200 симв.",
                            ),
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такая страна уже связана с другим производителем.",
                        },
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Страна должен состоять только из букв и пробелов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Страна должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=57,
                                message="Страна должен иметь максимальную длину 57 симв.",
                            ),
                        ],
                        verbose_name="Страна",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "required": "Эта контактная информация обязательна.",
                            "unique": "Такой номер телефона уже связан с другим производителем.",
                        },
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона может состоять из цифр, скобок и пробелов.",
                                regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={
                            "required": "Эта контактная информация обязательна.",
                            "unique": "Такой адрес электронной почты уже связан с другим производителем.",
                        },
                        max_length=254,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "other_info",
                    models.TextField(
                        blank=True, default="", verbose_name="Дополнительная информация"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical manufacturer",
                "verbose_name_plural": "historical manufacturers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupplier",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        default="...",
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название поставщика уже существует в системе.",
                        },
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название поставщика должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Название поставщика должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=255,
                                message="Название поставщика должен иметь максимальную длину 255 симв.",
                            ),
                        ],
                        verbose_name="Название поставщика",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        default="",
                        error_messages={
                            "required": "Это поле обязательно",
                            "unique": "Такое название поставщика уже существует в системе.",
                        },
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название поставщика должен состоять только из букв, цифр, пробелов и спецсимволов.",
                                regex="^[а-яА-ЯёЁa-zA-Z\\d!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?`~\\s]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3,
                                message="Название поставщика должен иметь минимальную длину 3 симв.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=255,
                                message="Название поставщика должен иметь максимальную длину 255 симв.",
                            ),
                        ],
                        verbose_name="Название поставщика на английском языке (для заграничных поставщиков)",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "inn",
                    models.CharField(
                        db_index=True,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ИНН должен содержать 10 или 12 цифр.",
                                regex="^\\d{10}(\\d{2})?$",
                            )
                        ],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="КПП должен содержать 9 цифр.", regex="^\\d{9}$"
                            )
                        ],
                        verbose_name="КПП",
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(
                        db_index=True,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ОГРН должен содержать 13 или 15 цифр.",
                                regex="^\\d{13}(\\d{2})?$",
                            )
                        ],
                        verbose_name="ОГРН",
                    ),
                ),
                (
                    "oktmo",
                    models.CharField(
                        db_index=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ОКТМО должен содержать 8 или 11 цифр.",
                                regex="^\\d{8}(\\d{3})?$",
                            )
                        ],
                        verbose_name="ОКТМО",
                    ),
                ),
                (
                    "pharma_license_number",
                    models.CharField(
                        db_index=True,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер лицензии (согласно РосЗдравНадзор) должен иметь формат 'ЛО-77-02-123456'",
                                regex="^ЛО-\\d{2}-\\d{2}-\\d{10}$",
                            )
                        ],
                        verbose_name="Номер лицензии (согласно РосЗдравНадзор)",
                    ),
                ),
                (
                    "pharma_license_date",
                    models.DateField(null=True, verbose_name="Дата выдачи лицензии"),
                ),
                (
                    "pharma_license_expiry",
                    models.DateField(null=True, verbose_name="Дата окончания лицензии"),
                ),
                (
                    "legal_address",
                    models.TextField(blank=True, verbose_name="Юридический адрес"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "required": "Данная контактная информация обязательна.",
                            "unique": "Такой номер телефона уже связан с другим поставщиком.",
                        },
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона может состоять из цифр, скобок и пробелов.",
                                regex="^(\\+7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={
                            "required": "Данная контактная информация обязательна.",
                            "unique": "Такой адрес электронной почты уже связан с другим поставщиком.",
                        },
                        max_length=254,
                        null=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical supplier",
                "verbose_name_plural": "historical suppliers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
